import { faker } from "@faker-js/faker";

const post = [
	{
		fullname: faker.name.fullName(),
		avatar: faker.internet.avatar(),
		comment: faker.lorem.text(),
		timestamp: "28m",
		likes: 2,
		replies: [
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
		],
	},
	{
		fullname: faker.name.fullName(),
		avatar: faker.internet.avatar(),
		comment: faker.lorem.text(),
		timestamp: "28m",
		likes: 2,
		replies: [
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
		],
	},
	{
		fullname: faker.name.fullName(),
		avatar: faker.internet.avatar(),
		comment: faker.lorem.text(),
		timestamp: "28m",
		likes: 2,
		replies: [
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
		],
	},
	{
		fullname: faker.name.fullName(),
		avatar: faker.internet.avatar(),
		comment: faker.lorem.text(),
		timestamp: "28m",
		likes: 2,
		replies: [
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
		],
	},
	{
		fullname: faker.name.fullName(),
		avatar: faker.internet.avatar(),
		comment: faker.lorem.text(),
		timestamp: "28m",
		likes: 2,
		replies: [
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
		],
	},
	{
		fullname: faker.name.fullName(),
		avatar: faker.internet.avatar(),
		comment: faker.lorem.text(),
		timestamp: "28m",
		likes: 2,
		replies: [],
	},
	{
		fullname: faker.name.fullName(),
		avatar: faker.internet.avatar(),
		comment: faker.lorem.text(),
		timestamp: "28m",
		likes: 2,
		replies: [
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
			{
				fullname: faker.name.fullName(),
				avatar: faker.internet.avatar(),
				comment: faker.lorem.text(),
				timestamp: "28m",
				likes: 2,
			},
		],
	},
];

export default post;
